// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/pneumacore.proto

package pneumacore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoveryPacketType int32

const (
	DiscoveryPacketType_UNSPECIFIED DiscoveryPacketType = 0
	DiscoveryPacketType_ACTIVE      DiscoveryPacketType = 1 // ядро почистило неактивные комнаты и прислало оставшиеся (активные)
	DiscoveryPacketType_SHARE       DiscoveryPacketType = 2 // другой пир прислал свои комнаты
)

// Enum value maps for DiscoveryPacketType.
var (
	DiscoveryPacketType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ACTIVE",
		2: "SHARE",
	}
	DiscoveryPacketType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"ACTIVE":      1,
		"SHARE":       2,
	}
)

func (x DiscoveryPacketType) Enum() *DiscoveryPacketType {
	p := new(DiscoveryPacketType)
	*p = x
	return p
}

func (x DiscoveryPacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiscoveryPacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_pneumacore_proto_enumTypes[0].Descriptor()
}

func (DiscoveryPacketType) Type() protoreflect.EnumType {
	return &file_proto_pneumacore_proto_enumTypes[0]
}

func (x DiscoveryPacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiscoveryPacketType.Descriptor instead.
func (DiscoveryPacketType) EnumDescriptor() ([]byte, []int) {
	return file_proto_pneumacore_proto_rawDescGZIP(), []int{0}
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_proto_pneumacore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pneumacore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_proto_pneumacore_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DiscoveryPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DiscoveryPacketType    `protobuf:"varint,1,opt,name=type,proto3,enum=pneumacore.DiscoveryPacketType" json:"type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Rooms         []*Room                `protobuf:"bytes,3,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryPacket) Reset() {
	*x = DiscoveryPacket{}
	mi := &file_proto_pneumacore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryPacket) ProtoMessage() {}

func (x *DiscoveryPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pneumacore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryPacket.ProtoReflect.Descriptor instead.
func (*DiscoveryPacket) Descriptor() ([]byte, []int) {
	return file_proto_pneumacore_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoveryPacket) GetType() DiscoveryPacketType {
	if x != nil {
		return x.Type
	}
	return DiscoveryPacketType_UNSPECIFIED
}

func (x *DiscoveryPacket) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DiscoveryPacket) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_pneumacore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pneumacore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_pneumacore_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MessagePacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *User                  `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Room          *Room                  `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePacket) Reset() {
	*x = MessagePacket{}
	mi := &file_proto_pneumacore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePacket) ProtoMessage() {}

func (x *MessagePacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pneumacore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePacket.ProtoReflect.Descriptor instead.
func (*MessagePacket) Descriptor() ([]byte, []int) {
	return file_proto_pneumacore_proto_rawDescGZIP(), []int{3}
}

func (x *MessagePacket) GetSender() *User {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *MessagePacket) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *MessagePacket) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessagePacket) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PositionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude      float64                `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Speed         float64                `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,5,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionInfo) Reset() {
	*x = PositionInfo{}
	mi := &file_proto_pneumacore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfo) ProtoMessage() {}

func (x *PositionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pneumacore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfo.ProtoReflect.Descriptor instead.
func (*PositionInfo) Descriptor() ([]byte, []int) {
	return file_proto_pneumacore_proto_rawDescGZIP(), []int{4}
}

func (x *PositionInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PositionInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PositionInfo) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *PositionInfo) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *PositionInfo) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *PositionInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SosPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *User                  `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Position      *PositionInfo          `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SosPacket) Reset() {
	*x = SosPacket{}
	mi := &file_proto_pneumacore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SosPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SosPacket) ProtoMessage() {}

func (x *SosPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pneumacore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SosPacket.ProtoReflect.Descriptor instead.
func (*SosPacket) Descriptor() ([]byte, []int) {
	return file_proto_pneumacore_proto_rawDescGZIP(), []int{5}
}

func (x *SosPacket) GetSender() *User {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *SosPacket) GetPosition() *PositionInfo {
	if x != nil {
		return x.Position
	}
	return nil
}

var File_proto_pneumacore_proto protoreflect.FileDescriptor

const file_proto_pneumacore_proto_rawDesc = "" +
	"\n" +
	"\x16proto/pneumacore.proto\x12\n" +
	"pneumacore\"*\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8c\x01\n" +
	"\x0fDiscoveryPacket\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.pneumacore.DiscoveryPacketTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12&\n" +
	"\x05rooms\x18\x03 \x03(\v2\x10.pneumacore.RoomR\x05rooms\"*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x91\x01\n" +
	"\rMessagePacket\x12(\n" +
	"\x06sender\x18\x01 \x01(\v2\x10.pneumacore.UserR\x06sender\x12$\n" +
	"\x04room\x18\x02 \x01(\v2\x10.pneumacore.RoomR\x04room\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xb4\x01\n" +
	"\fPositionInfo\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x03 \x01(\x01R\baltitude\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x01R\x05speed\x12\x1a\n" +
	"\baccuracy\x18\x05 \x01(\x01R\baccuracy\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"k\n" +
	"\tSosPacket\x12(\n" +
	"\x06sender\x18\x01 \x01(\v2\x10.pneumacore.UserR\x06sender\x124\n" +
	"\bposition\x18\x02 \x01(\v2\x18.pneumacore.PositionInfoR\bposition*=\n" +
	"\x13DiscoveryPacketType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\t\n" +
	"\x05SHARE\x10\x02B\x0eZ\f./pneumacoreb\x06proto3"

var (
	file_proto_pneumacore_proto_rawDescOnce sync.Once
	file_proto_pneumacore_proto_rawDescData []byte
)

func file_proto_pneumacore_proto_rawDescGZIP() []byte {
	file_proto_pneumacore_proto_rawDescOnce.Do(func() {
		file_proto_pneumacore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pneumacore_proto_rawDesc), len(file_proto_pneumacore_proto_rawDesc)))
	})
	return file_proto_pneumacore_proto_rawDescData
}

var file_proto_pneumacore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_pneumacore_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_pneumacore_proto_goTypes = []any{
	(DiscoveryPacketType)(0), // 0: pneumacore.DiscoveryPacketType
	(*Room)(nil),             // 1: pneumacore.Room
	(*DiscoveryPacket)(nil),  // 2: pneumacore.DiscoveryPacket
	(*User)(nil),             // 3: pneumacore.User
	(*MessagePacket)(nil),    // 4: pneumacore.MessagePacket
	(*PositionInfo)(nil),     // 5: pneumacore.PositionInfo
	(*SosPacket)(nil),        // 6: pneumacore.SosPacket
}
var file_proto_pneumacore_proto_depIdxs = []int32{
	0, // 0: pneumacore.DiscoveryPacket.type:type_name -> pneumacore.DiscoveryPacketType
	1, // 1: pneumacore.DiscoveryPacket.rooms:type_name -> pneumacore.Room
	3, // 2: pneumacore.MessagePacket.sender:type_name -> pneumacore.User
	1, // 3: pneumacore.MessagePacket.room:type_name -> pneumacore.Room
	3, // 4: pneumacore.SosPacket.sender:type_name -> pneumacore.User
	5, // 5: pneumacore.SosPacket.position:type_name -> pneumacore.PositionInfo
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_pneumacore_proto_init() }
func file_proto_pneumacore_proto_init() {
	if File_proto_pneumacore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pneumacore_proto_rawDesc), len(file_proto_pneumacore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pneumacore_proto_goTypes,
		DependencyIndexes: file_proto_pneumacore_proto_depIdxs,
		EnumInfos:         file_proto_pneumacore_proto_enumTypes,
		MessageInfos:      file_proto_pneumacore_proto_msgTypes,
	}.Build()
	File_proto_pneumacore_proto = out.File
	file_proto_pneumacore_proto_goTypes = nil
	file_proto_pneumacore_proto_depIdxs = nil
}
